### ISSUE TITLE
No RSS feed

### ISSUE THREAD

**Issue by kuba-orlik** [allegro/blog#93]
I enjoy articles from your blog, but there's no way to easily subscribe to it! Adding an RSS feed would be greatly appreciated! 🙏

**Comment by kuba-orlik** [comment]
For now the most approachable option is scraping, so I've set up a temporary workaround feed: https://huginn.kuba-orlik.name/users/1/web_requests/307/allegro-blog-rss.xml

It will only fetch the HTML of your blog once every 12h

**Comment by mkosmul** [comment]
Have a look at https://blog.allegro.tech/feed.xml
I guess we should highlight the feed more on the web page - @bgalek to the rescue!

**Comment by bgalek** [comment]
@kuba-orlik I'll add rss autodiscovery meta tag, so browsers will show you rss feed link ;)
